import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { client } from "../src/features/Shopify"
import { useState } from 'react'
import { addProductToCart, getCart } from '../src/features/Shopify/Cart'
import Router from "next/router"

export default function Home({ products }) {
  console.log(products)

  const addProduct = (variantId) => {
    addProductToCart({ quantity: 1, variantId })
  }

  const goToCheckout = async () => {
    const { webUrl } = await getCart();
    Router.replace(webUrl);
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>RBS SU Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>RBS SU Store</h1>
      <button onClick={goToCheckout}>Go to Shopify checkout</button>
      {/* This is here for spacing, I know - lazy */}
      <p></p>
      {products.map((product) => (
        <div key={product.key}>
          <img src={product.images[0].src} width={300} height={300} />
          <p>{product.title}</p>
          <button onClick={() => addProduct(product.variants[0].id)}>Add product to cart</button>
        </div>
      ))}
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const products = await client.product.fetchAll(); // Fetch product
  const infos = await client.shop.fetchInfo(); // Fetch shop Info if you think about SEO and title and ... to your page
  const policies = await client.shop.fetchPolicies(); // fetch shop policy if you have any 
  return {
    props: {
      infos: JSON.parse(JSON.stringify(infos)),
      policies: JSON.parse(JSON.stringify(policies)),
      products: JSON.parse(JSON.stringify(products)),
    },
  };
};
